# Generated by Django 4.2.9 on 2024-01-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_like_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
